- name: Configuring the {{COMPONENT}} repo 
  ansible.builtin.copy:
    src: mongo.repo 
    dest: /etc/yum.repos.d/mongodb.repo
    remote_src: yes

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
      name: mongodb-org 
      state: present

- name: Starting {{COMPONENT}} 
  systemd:
    name: nginx
    state: mongod 
    enabled: yes
