- name: Copying the prometheus config 
  ansible.builtin.template:
    src: prometheus.yml  
    dest: /opt/prometheus/prometheus.yml

- name: Restarting Prometheus  
  systemd:
    name: prometheus
    state: restarted
    enabled: yes
    daemon_reload: yes 

- name: Waiting for prometheus port to be in listening state 
  ansible.builtin.wait_for:
    port: 9090 
    delay: 10 
    timeout: 20
