- name: Creating {{APPUSER}}
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: roboshop app user 
  register: USERINFO 

- name: Printing the variable 
  ansible.builtin.debug:
    msg: Value of the OUT is {{USERINFO}} 

- name: Installing app dependencies
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt 
    executable: pip3