- name: Configuring Nodejs
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -

- name: Installing Nodejs
  ansible.builtin.package:
      name: nodejs  
      state: present

- name: Creating App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

# Downloads the code directly from Github 
# - name: Download and extracting {{COMPONENT}}
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download_and_extract

- name: Download and extracting {{COMPONENT}} from Nexus
  ansible.builtin.include_role:
    name: common
    tasks_from: download_from_nexus

# Only use this when you want to download the code from Github and create artifacts, with CI in place, we always use NEXUS.
# - name: Generating Artifacts with npm install 
#   community.general.npm:
#     path: /home/{{APPUSER}}/{{COMPONENT}}/ 

- name: Configuring {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc 

- name: Configuring Name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name